import './globals.css'
import '../../node_modules/bootstrap-icons/font/bootstrap-icons.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Apple (India)',
  description: 'Generated by create next app',
  icons : {
    url: "/favicon.png",
    type: "image/png",
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
